field: 1dc9dda5-0e44-42f8-93bf-6f846eb9922f # Box Matrix
fieldLayouts:
  7b7dc8d2-7f7d-44ce-b8db-54f2f47c5f66:
    tabs:
      -
        elements:
          -
            fieldUid: 2d94dd5b-59fa-4fdd-bd4e-23b60796bbde # Box Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8a091e80-1113-44cb-b73f-cb7e1cdd26b5
            warning: null
            width: 100
          -
            fieldUid: 0b4e7730-a3bc-4b08-87ae-a7971bc6ad67 # Subtext
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 344b73da-cfb7-4d37-a3ce-91de34959132
            warning: null
            width: 100
          -
            fieldUid: a9516c1c-e914-43fa-9448-3ce930e339ac # Box URL
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 93d2878f-9efb-4e93-9d97-8e150c84dfa4
            warning: null
            width: 100
          -
            fieldUid: a4ed7be9-7105-4e16-8351-4816b81c704f # Button Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a7d7ce5d-b9ee-46f6-94e0-82a3cb29a6ee
            warning: null
            width: 100
          -
            fieldUid: 6c824489-1b68-499c-9c9d-f4c72e94be79 # Category
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fcc7590c-b5ee-40cc-b565-2124364b20c0
            warning: null
            width: 100
        name: Content
        uid: fab1e778-0dc1-4251-9283-b041dcbdc8f1
fields:
  0b4e7730-a3bc-4b08-87ae-a7971bc6ad67: # Subtext
    columnSuffix: zeskisam
    contentColumnType: text
    fieldGroup: null
    handle: subtext
    instructions: null
    name: Subtext
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: 'Enter the subtext for the box'
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  2d94dd5b-59fa-4fdd-bd4e-23b60796bbde: # Box Title
    columnSuffix: txxvughz
    contentColumnType: text
    fieldGroup: null
    handle: boxTitle
    instructions: null
    name: 'Box Title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: 'Enter a title for the box'
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  6c824489-1b68-499c-9c9d-f4c72e94be79: # Category
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: category
    instructions: null
    name: Category
    searchable: false
    settings:
      allowLimit: false
      allowMultipleSources: false
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maxRelations: null
      minRelations: null
      selectionLabel: null
      showSiteMenu: true
      source: 'group:97b8480e-a18a-423b-a4ca-5c544c87137a' # Type of Number
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Categories
  a4ed7be9-7105-4e16-8351-4816b81c704f: # Button Text
    columnSuffix: kcfcwujh
    contentColumnType: text
    fieldGroup: null
    handle: buttonText
    instructions: null
    name: 'Button Text'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: 'Include the text to be displayed in button'
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  a9516c1c-e914-43fa-9448-3ce930e339ac: # Box URL
    columnSuffix: mzjhynhg
    contentColumnType: string(255)
    fieldGroup: null
    handle: boxUrl
    instructions: null
    name: 'Box URL'
    searchable: false
    settings:
      maxLength: 255
      types:
        - url
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
handle: boxMatrix
name: 'Box Matrix'
sortOrder: 1
