fieldLayouts:
  6301baf5-ad44-434a-b5e3-c4c880e3df41:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: c01cd7e5-2024-4bc8-bf4a-0e13d39709bc
            warning: null
            width: 100
          -
            fieldUid: e58bfe8c-37a0-4118-9a4c-bab6becc27f1 # Subheader
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8d9e94c6-07f9-41e2-8014-b5250bce5727
            warning: null
            width: 100
          -
            fieldUid: f8588823-aa23-4ab7-961e-ee92b9fff542 # Blog Entry
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 48a075f3-d6e1-4dd0-8e38-8ca54d289896
            warning: null
            width: 100
        name: Content
        uid: 529038c5-989e-4ee1-b351-d321f68d38be
handle: blog
hasTitleField: true
name: Blog
section: 043ad44f-4416-4a63-8c7d-2b28d78cf2e6 # Blog
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
