fieldLayouts:
  87bc3d37-07a4-4854-afa9-69f7ff8052b1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 297bad44-b9c5-4738-a2dc-4bf1edc56b87
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9d9c082e-2964-402c-a340-cf2b6127eef9 # Box Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 81683e98-7973-454c-a255-e87f28421de4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e01820d5-d458-4b66-9686-e1c1c9f7788a # Box Subtext
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bd50835b-606f-40c6-9dad-bda40d3eded8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 79cc44ca-2dc7-4ea0-baa9-c8c9d43c2c2a # Box Images
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 412ccaaf-30eb-4460-b625-398015423233
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d28e128e-1c93-466a-aa51-e63fde158210 # Box Button
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 286605f5-31f3-4247-834a-edb7253cd789
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 24be0cca-4df1-43ba-8e79-72f0ab3c5a7b # Button URL
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e9c8b029-490b-437f-9691-63edfefcb9f9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fcc7d786-4378-4f36-b3c2-75906707a81f # Box Category
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1223c804-f8d6-449e-9bb7-609a0d8b06ec
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ddb975fb-59fd-4fdd-899b-553acbebf86d
        userCondition: null
handle: boxes
hasTitleField: true
name: Boxes
section: 77c9e69f-7628-4f93-9a54-cdfdb8009ac1 # Boxes
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
