defaultPlacement: end
fieldLayouts:
  cd45a943-282a-4a46-a537-9a1ffdacb784:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: e15f1721-17c4-4ccc-92a0-9e278793ad95
            warning: null
            width: 100
          -
            fieldUid: 45150b46-6997-42f3-8551-b9250ddb125e # Page Background
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 49a9ebaf-40f7-4930-a866-d6842f66f1f6
            warning: null
            width: 100
        name: Content
        uid: bb52c3bb-529a-4993-8b01-fd03681ed1a5
handle: typeOfNumber
name: 'Type of Number'
siteSettings:
  c468402d-2f03-40e5-a951-1305998c8597: # Bonfire Craft
    hasUrls: true
    template: category.html
    uriFormat: 'type-of-number/{slug}'
structure:
  maxLevels: null
  uid: edc4bf92-feea-46af-b663-11af6ac391d9
