defaultPlacement: end
fieldLayouts:
  55c6535d-1bc8-434e-b7a6-9bbd72f3dd90:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: ea6aa189-cdea-4cb7-ac26-750bda556a28
            warning: null
            width: 100
        name: Content
        uid: 2511bc9c-1276-4250-99e2-eeabe6f3ef57
handle: typeOfNumber
name: 'Type of Number'
siteSettings:
  c468402d-2f03-40e5-a951-1305998c8597: # Bonfire Craft
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: f04255bb-5193-4bf3-aa52-047beb4ec84d
