fieldLayouts:
  0f0f3f62-96e6-444d-954b-ef1d499e5602:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: d86dc67b-5135-4a55-b945-cd8dda92b01b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7dc9d025-0739-490f-a3c6-1929e31c4dba
        userCondition: null
fs: boxImages
handle: boxImages
name: 'Box Images'
sortOrder: 2
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
