columnSuffix: anrjzzhv
contentColumnType: text
fieldGroup: 0ca6b6ea-51af-442c-8ec1-67d19b75b009 # Common
handle: boxSubtext
instructions: null
name: 'Box Subtext'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: 'Enter subtext for the boxes'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
