columnSuffix: exqsckyt
contentColumnType: string(255)
fieldGroup: 0ca6b6ea-51af-442c-8ec1-67d19b75b009 # Common
handle: buttonUrl
instructions: null
name: 'Button URL'
searchable: false
settings:
  maxLength: 255
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
