dateModified: 1656435055
email:
  fromEmail: mitch@hellobonfire.com
  fromName: 'Bonfire Craft'
  transportType: craft\mail\transportadapters\Sendmail
fs:
  learning:
    hasUrls: true
    name: Learning
    settings:
      path: '@webroot/media'
    type: craft\fs\Local
    url: '@web/media'
meta:
  __names__:
    0b4e7730-a3bc-4b08-87ae-a7971bc6ad67: Subtext # Subtext
    0ca6b6ea-51af-442c-8ec1-67d19b75b009: Common # Common
    0cf3234f-22a2-4771-b52c-f3f2946bad24: 'Type of Number' # Type of Number
    1dc9dda5-0e44-42f8-93bf-6f846eb9922f: 'Box Matrix' # Box Matrix
    2d94dd5b-59fa-4fdd-bd4e-23b60796bbde: 'Box Title' # Box Title
    2df774ce-cda6-438a-9c97-6be6164e50a9: 'Bonfire Craft' # Bonfire Craft
    3b57a8ca-84c1-43dd-a601-b217ec298535: Blog # Blog
    3ee075a2-ce3a-40e9-9684-c24d186be8f0: 'Box Matrix' # Box Matrix
    4cb3aaa5-2729-4446-94cf-06a1eac2cb4f: 'Page Description' # Page Description
    6a634188-be38-46f4-a521-a891fdf7c331: 'Main Navigation' # Main Navigation
    6c824489-1b68-499c-9c9d-f4c72e94be79: Category # Category
    9b0de38d-72b7-4341-b3de-a7870bc781bf: 'Page Background' # Page Background
    9d9c082e-2964-402c-a340-cf2b6127eef9: 'Box Title' # Box Title
    21eb0b24-b45a-4aa1-838d-1b6105cd7979: Home # Home
    24be0cca-4df1-43ba-8e79-72f0ab3c5a7b: 'Button URL' # Button URL
    043ad44f-4416-4a63-8c7d-2b28d78cf2e6: Blog # Blog
    77c9e69f-7628-4f93-9a54-cdfdb8009ac1: Boxes # Boxes
    1097f618-43c7-44d3-865d-82f9543dc597: 'Blog Entries' # Blog Entries
    6810ae13-1880-4b97-bdf6-1e0dad2a677b: 'Blog Content' # Blog Content
    45150b46-6997-42f3-8551-b9250ddb125e: 'Page Background' # Page Background
    486106d1-f090-4258-8609-0299cb1c175b: Boxes # Boxes
    742694d0-89a4-4d0c-bf6c-46bf262f060c: Boxes # Boxes
    7054554a-3706-4536-b965-b0331a162a6c: Home # Home
    36199568-9491-4132-b644-51319dbef53b: Blog # Blog
    a4ed7be9-7105-4e16-8351-4816b81c704f: 'Button Text' # Button Text
    a9516c1c-e914-43fa-9448-3ce930e339ac: 'Box URL' # Box URL
    b1df6924-c61e-4059-94a1-692c288f6925: 'Public Schema' # Public Schema
    c468402d-2f03-40e5-a951-1305998c8597: 'Bonfire Craft' # Bonfire Craft
    d28e128e-1c93-466a-aa51-e63fde158210: 'Box Button' # Box Button
    e01820d5-d458-4b66-9686-e1c1c9f7788a: 'Box Subtext' # Box Subtext
    e58bfe8c-37a0-4118-9a4c-bab6becc27f1: Subheader # Subheader
    f8e89ea8-41cd-4bcb-ab1f-17f572ad9ab7: 'Page Title' # Page Title
    f46f9039-171f-43f2-953d-5f2f7e4b49cf: Default # Default
    f8588823-aa23-4ab7-961e-ee92b9fff542: 'Blog Entry' # Blog Entry
    fcc7d786-4378-4f36-b3c2-75906707a81f: 'Box Category' # Box Category
plugins:
  navigation:
    edition: standard
    enabled: true
    licenseKey: D6J26XVS2DHNSM0AZW5G5KKP
    schemaVersion: 2.0.2
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  twigpack:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: pro
  live: true
  name: 'Bonfire Craft'
  schemaVersion: 4.0.0.9
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
