defaultPlacement: end
enableVersioning: true
handle: blog
name: Blog
propagationMethod: all
siteSettings:
  c468402d-2f03-40e5-a951-1305998c8597: # Bonfire Craft
    enabledByDefault: true
    hasUrls: true
    template: blog
    uriFormat: blog
type: single
